"""Inheritance example package."""

from .subpckg_inheritance import dummy_inheritance
from .subpckg_inheritance_nested_association import dummy_inheritance_nested_association
from .subpckg_inheritance_nested_inheritance import dummy_inheritance_nested_inheritance
